// <auto-generated />
using System;
using AutomotiveForumSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutomotiveForumSystem.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20240117103741_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AutomotiveForumSystem.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            Name = "Tuning"
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            Name = "Engines"
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = false,
                            Name = "Suspension"
                        },
                        new
                        {
                            Id = 4,
                            IsDeleted = false,
                            Name = "Electronics"
                        });
                });

            modelBuilder.Entity("AutomotiveForumSystem.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(8192)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("ParentCommentId")
                        .HasColumnType("int");

                    b.Property<int>("PostID")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentCommentId");

                    b.HasIndex("PostID");

                    b.HasIndex("UserID");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Awesome. I will follow your tutorial to tune my supra.",
                            CreateDate = new DateTime(2024, 1, 17, 12, 37, 40, 991, DateTimeKind.Local).AddTicks(2404),
                            IsDeleted = false,
                            PostID = 1,
                            UserID = 1
                        },
                        new
                        {
                            Id = 2,
                            Content = "Comment number 2 with ensured min length.",
                            CreateDate = new DateTime(2024, 1, 17, 12, 37, 40, 991, DateTimeKind.Local).AddTicks(2410),
                            IsDeleted = false,
                            PostID = 2,
                            UserID = 2
                        },
                        new
                        {
                            Id = 3,
                            Content = "Comment number 3 with ensured min length.",
                            CreateDate = new DateTime(2024, 1, 17, 12, 37, 40, 991, DateTimeKind.Local).AddTicks(2413),
                            IsDeleted = false,
                            PostID = 3,
                            UserID = 3
                        },
                        new
                        {
                            Id = 4,
                            Content = "Comment number 4 with ensured min length.",
                            CreateDate = new DateTime(2024, 1, 17, 12, 37, 40, 991, DateTimeKind.Local).AddTicks(2417),
                            IsDeleted = false,
                            PostID = 4,
                            UserID = 1
                        },
                        new
                        {
                            Id = 5,
                            Content = "Comment number 5 with ensured min length.",
                            CreateDate = new DateTime(2024, 1, 17, 12, 37, 40, 991, DateTimeKind.Local).AddTicks(2420),
                            IsDeleted = false,
                            PostID = 4,
                            UserID = 1
                        },
                        new
                        {
                            Id = 6,
                            Content = "Comment number 6 with ensured min length.",
                            CreateDate = new DateTime(2024, 1, 17, 12, 37, 40, 991, DateTimeKind.Local).AddTicks(2424),
                            IsDeleted = false,
                            PostID = 4,
                            UserID = 1
                        },
                        new
                        {
                            Id = 7,
                            Content = "This is a reply.",
                            CreateDate = new DateTime(2024, 1, 17, 12, 37, 40, 991, DateTimeKind.Local).AddTicks(2428),
                            IsDeleted = false,
                            ParentCommentId = 6,
                            PostID = 4,
                            UserID = 2
                        });
                });

            modelBuilder.Entity("AutomotiveForumSystem.Models.Like", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("Likes");
                });

            modelBuilder.Entity("AutomotiveForumSystem.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(8192)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("TotalLikesCount")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryID");

                    b.HasIndex("UserID");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryID = 1,
                            Content = "Step by step tutorial.",
                            CreateDate = new DateTime(2024, 1, 17, 12, 37, 40, 991, DateTimeKind.Local).AddTicks(2310),
                            IsDeleted = false,
                            Title = "This is a post about the tuning of my supra.",
                            TotalLikesCount = 0,
                            UserID = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoryID = 2,
                            Content = "Step by step tutorial.",
                            CreateDate = new DateTime(2024, 1, 17, 12, 37, 40, 991, DateTimeKind.Local).AddTicks(2360),
                            IsDeleted = false,
                            Title = "here i will talk about the supra mk4's 2jz engine",
                            TotalLikesCount = 0,
                            UserID = 1
                        },
                        new
                        {
                            Id = 3,
                            CategoryID = 2,
                            Content = "Step by step tutorial.",
                            CreateDate = new DateTime(2024, 1, 17, 12, 37, 40, 991, DateTimeKind.Local).AddTicks(2364),
                            IsDeleted = false,
                            Title = "the engine is incredibly small like all japanese engines",
                            TotalLikesCount = 0,
                            UserID = 1
                        },
                        new
                        {
                            Id = 4,
                            CategoryID = 3,
                            Content = "Step by step tutorial.",
                            CreateDate = new DateTime(2024, 1, 17, 12, 37, 40, 991, DateTimeKind.Local).AddTicks(2368),
                            IsDeleted = false,
                            Title = "the suspension on this car is not the best but it does the job",
                            TotalLikesCount = 0,
                            UserID = 1
                        },
                        new
                        {
                            Id = 5,
                            CategoryID = 4,
                            Content = "Step by step tutorial.",
                            CreateDate = new DateTime(2024, 1, 17, 12, 37, 40, 991, DateTimeKind.Local).AddTicks(2372),
                            IsDeleted = false,
                            Title = "this is a very old car so there's very few electronics on it",
                            TotalLikesCount = 0,
                            UserID = 1
                        });
                });

            modelBuilder.Entity("AutomotiveForumSystem.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "john@mail.com",
                            FirstName = "John",
                            IsAdmin = true,
                            IsBlocked = false,
                            IsDeleted = false,
                            LastName = "Smith",
                            Password = "1234",
                            PhoneNumber = "0888 102 030",
                            UserName = "jonkata"
                        },
                        new
                        {
                            Id = 2,
                            Email = "steven@mail.com",
                            FirstName = "Steven",
                            IsAdmin = false,
                            IsBlocked = false,
                            IsDeleted = false,
                            LastName = "Solberg",
                            Password = "1020",
                            UserName = "stevie"
                        },
                        new
                        {
                            Id = 3,
                            Email = "ivan@mail.com",
                            FirstName = "Ivan",
                            IsAdmin = false,
                            IsBlocked = false,
                            IsDeleted = false,
                            LastName = "Ivanov",
                            Password = "3344",
                            UserName = "vanko_54"
                        });
                });

            modelBuilder.Entity("AutomotiveForumSystem.Models.Comment", b =>
                {
                    b.HasOne("AutomotiveForumSystem.Models.Comment", null)
                        .WithMany("Replies")
                        .HasForeignKey("ParentCommentId");

                    b.HasOne("AutomotiveForumSystem.Models.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AutomotiveForumSystem.Models.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AutomotiveForumSystem.Models.Like", b =>
                {
                    b.HasOne("AutomotiveForumSystem.Models.Post", "Post")
                        .WithMany("Likes")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AutomotiveForumSystem.Models.User", "User")
                        .WithMany("Likes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AutomotiveForumSystem.Models.Post", b =>
                {
                    b.HasOne("AutomotiveForumSystem.Models.Category", "Category")
                        .WithMany("Posts")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutomotiveForumSystem.Models.User", "User")
                        .WithMany("Posts")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AutomotiveForumSystem.Models.Category", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("AutomotiveForumSystem.Models.Comment", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("AutomotiveForumSystem.Models.Post", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Likes");
                });

            modelBuilder.Entity("AutomotiveForumSystem.Models.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Likes");

                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
